# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "54dbcb87db6101444ef1ce9b7928dd98"
name = "myapp"
handle = "myapp-1141"
application_url = "https://myapp-1e4e.onrender.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://myapp-1e4e.onrender.com/api/auth" ]

[pos]
embedded = false
